### ISSUE TITLE
Ch10: Internal GIS bridges chapter review

### ISSUE THREAD

**Issue by Nowosad** [geocompx/geocompr#881]

**Comment by Nowosad** [comment]
@jannes-m it would be good if you could also incorporate changes from https://github.com/Robinlovelace/geocompr/issues/412.

**Comment by jannes-m** [comment]
Hey @Nowosad,
first of all, thanks again for taking over the r-gis bridges chapter and the rewrite!
I have just started reviewing it, so this is sill work-in-progress (see also #883). I will update this comment with further comments:

1. Shouldn't we display at least some of the output of `qgis_show_help("native:union")`. Otherwise it's quite hard for the reader to understand how we came up with the parameter names `INPUT`, `OUTPUT` and `OVERLAY`. And in the second example `qgis_show_help("grass:v.clean")` we should state explicitly that the output is not shown.
2. I think we should also mention that though you can use r spatial objects as inputs for **qgisprocess**, it is always computationally less demanding to use a file already living on disk since this way we avoid to load the object into R just to let **qgisprocess** save it back for the further processing in QGIS.
3. Though `terra::terrain()` is an interesting function, it is a bit out of scope here, when we are actually talking about integrations with 3rd party tools (like QGIS, etc.). Maybe we could skip the `terra::terrain()` code example and just say that you can also natively compute terrain charasterics in R but that there are many more such as the sagawetness index and geomorphons?

**Comment by Nowosad** [comment]
Hi @jannes-m -- yes to all. Can you do it?
